-- Table T_BRAND
CREATE TABLE T_BRAND(
	ID VARCHAR(32) NOT NULL,
	NAME VARCHAR(35) NOT NULL,
	CREATION_DATE TIMESTAMP NOT NULL,
    MODIFIED_DATE TIMESTAMP NOT NULL,
    CREATED_BY VARCHAR(32) NOT NULL,
    MODIFIED_BY VARCHAR(32) NOT NULL
);

-- Table FRIEND_LIST
CREATE TABLE T_PRODUCT(
	ID VARCHAR(32) NOT NULL,
	BRAND_ID VARCHAR(32) NOT NULL REFERENCES T_BRAND(ID),
	NAME VARCHAR(35) NOT NULL,
	SIZE INT NOT NULL,
	COLOR INT NOT NULL,
    CREATION_DATE TIMESTAMP NOT NULL,
    MODIFIED_DATE TIMESTAMP NOT NULL,
    CREATED_BY VARCHAR(32) NOT NULL,
    MODIFIED_BY VARCHAR(32) NOT NULL,
	PRIMARY KEY (ID),
    INDEX FK_PRODUCT_BRAND_IDX (BRAND_ID ASC)
);

COMMIT;